Update the app Italian resource
jonan/ForkHub pull request #320
Opened 2017-09-09 14:03 UTC by marcoM32

2017-09-19 21:07 UTC, jonan commented
Please indent the file using spaces instead of tabs.

2017-10-25 19:39 UTC, marcoM32 commented
Because this translation has not yet been included

2017-10-30 14:12 UTC, jonan commented
It's still reindenting all the file: https://github.com/jonan/ForkHub/pull/320/files

Compare the diff with this one: https://github.com/jonan/ForkHub/pull/324/files
Only the modified lines should appear in the diff.

2017-11-03 17:19 UTC, marcoM32 commented
Now the merge should be possible...

2017-11-11 19:44 UTC, marcoM32 commented
Please add my work on the official repo

2017-11-13 15:49 UTC, jonan requested changes
You still have a few places with wrong characters.

I think you're using a invalid encoding.

2017-11-13 15:49 UTC, jonan commented on app/src/main/res/values-it/strings.xml
> +    <string name="issue_event_label_assigned">衳tata assegnata da %1$s</string>
example

2017-11-13 15:49 UTC, jonan commented on app/src/main/res/values-it/strings.xml
> +    <string name="enter_otp_code_message">L\'autenticazione a doppio step 衡bilitata per il tuo account. Inserisci il codice di autenticazione per verificare la tua identit஼/string>
example

2017-11-13 15:49 UTC, jonan commented on app/src/main/res/values-it/strings.xml
> +    <string name="authenticator_conflict_message">E\' giࡳtata configurata un\' altra applicazione per l\' autenticazione di GitHub.\n\nPer utilizzare l\'app di Github rimuovi l\'altra applicazione da
example

2018-01-09 22:15 UTC, newtires approved these changes

2018-10-29 14:49 UTC, Tawat99 approved these changes

2019-11-14 08:16 UTC, closed without merging